import { execSync } from 'child_process'
import { writeFileSync, unlinkSync, existsSync, statSync, mkdirSync } from 'fs'
import { join } from 'path'
import { tmpdir } from 'os'
import { loadState } from '../state'
import * as tmux from '../tmux'

// ── Pure utilities ───────────────────────────────────────────────────────────

export function intervalToCron(interval: string): string {
  const m = interval.match(/^(\d+)(m|h|d)$/)
  if (!m) throw new Error(`Invalid interval "${interval}". Use format: 30m, 1h, 6h`)
  const n = parseInt(m[1], 10)
  const unit = m[2]
  if (unit === 'm') {
    if (n <= 0 || 60 % n !== 0) throw new Error(`Minute interval must divide evenly into 60 (got ${n})`)
    return `*/${n} * * * *`
  }
  if (unit === 'h') {
    if (n <= 0 || 24 % n !== 0) throw new Error(`Hour interval must divide evenly into 24 (got ${n})`)
    return n === 24 ? '0 0 * * *' : `0 */${n} * * *`
  }
  if (unit === 'd') {
    if (n !== 1) throw new Error(`Day interval only supports 1d`)
    return '0 0 * * *'
  }
  throw new Error(`Invalid interval unit "${unit}"`)
}

export function cronToHuman(expr: string): string {
  const parts = expr.split(' ')
  if (parts.length !== 5) return expr
  const [min, hour, dom, month, dow] = parts

  if (dom !== '*' || month !== '*') return expr

  // Every N minutes: */N * * * *
  if (min.startsWith('*/') && hour === '*' && dow === '*') {
    return `every ${min.slice(2)}m`
  }
  // Every hour: 0 * * * *  (or */1 *)
  if ((min === '0' || min === '*/60') && hour === '*' && dow === '*') {
    return 'every 1h'
  }
  // Every N hours: 0 */N * * *
  if (min === '0' && hour.startsWith('*/') && dow === '*') {
    return `every ${hour.slice(2)}h`
  }
  // Daily at midnight: 0 0 * * *
  if (min === '0' && hour === '0' && dow === '*') {
    return 'daily 0:00'
  }
  // Specific time daily: M H * * *  (no wildcards)
  if (!min.includes('*') && !min.includes('/') && !hour.includes('*') && !hour.includes('/') && dow === '*') {
    return `daily ${hour}:${min.padStart(2, '0')}`
  }
  return expr
}

export function parseTimeout(timeout: string): number {
  const m = timeout.match(/^(\d+)(m|s)$/)
  if (!m) throw new Error(`Invalid timeout "${timeout}". Use format: 5m or 30s`)
  const n = parseInt(m[1], 10)
  return m[2] === 'm' ? n * 60 : n
}

// ── Script generation ────────────────────────────────────────────────────────

export interface ScriptOpts {
  send?: string
  spawn?: boolean
  preset?: string
  dir?: string
  timeoutSecs?: number
  parent?: string
  bootstrap?: string
  binPath?: string // e.g. /Users/x/.bun/bin:/opt/homebrew/bin:...
}

export function generateScript(name: string, opts: ScriptOpts): string {
  const pathVal = opts.binPath ?? '/Users/twaldin/.bun/bin:/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin'
  const dirPart = opts.dir ? ` --dir ${opts.dir}` : ''
  const parentPart = opts.parent && opts.parent !== 'human' ? ` --parent ${opts.parent}` : ''
  const presetPart = opts.preset ? ` --preset ${opts.preset}` : ''

  function shellQuote(s: string): string {
    return `'${s.replace(/'/g, "'\\''")}'`
  }

  const bootstrapPart = opts.bootstrap ? ` ${shellQuote(opts.bootstrap)}` : ''

  if (opts.send) {
    const msg = shellQuote(opts.send)
    return [
      '#!/bin/bash',
      `# flt cron-${name} — sends message to persistent ${name} agent`,
      '# Generated by flt cron add',
      '',
      'export FLT_AGENT_NAME=cron',
      `export PATH="${pathVal}"`,
      '',
      `if flt list 2>/dev/null | grep -q "^.*${name}"; then`,
      `  flt send ${name} ${msg}`,
      `  echo "$(date -u +%Y-%m-%dT%H:%M:%SZ) sent message to ${name}"`,
      'else',
      `  flt spawn ${name}${presetPart}${dirPart}${parentPart} --no-worktree${bootstrapPart} 2>&1`,
      `  echo "$(date -u +%Y-%m-%dT%H:%M:%SZ) spawned ${name}"`,
      'fi',
      '',
    ].join('\n')
  }

  // spawn (ephemeral) pattern
  const timeoutSecs = opts.timeoutSecs ?? 300
  const intervals = Math.ceil(timeoutSecs / 10)
  return [
    '#!/bin/bash',
    `# flt cron-${name} — spawns ephemeral ${name} agent, waits, kills`,
    '# Generated by flt cron add',
    '',
    'export FLT_AGENT_NAME=cron',
    `export PATH="${pathVal}"`,
    '',
    '# Check if already running',
    `if flt list 2>/dev/null | grep -q "${name}.*running"; then`,
    `  echo "$(date -u +%Y-%m-%dT%H:%M:%SZ) ${name} already running, skipping"`,
    '  exit 0',
    'fi',
    '',
    "INBOX_BEFORE=$(wc -l < ~/.flt/inbox.log 2>/dev/null || echo 0)",
    '',
    `flt spawn ${name}${presetPart}${dirPart}${parentPart} --no-worktree${bootstrapPart} 2>&1`,
    `echo "$(date -u +%Y-%m-%dT%H:%M:%SZ) ${name} spawned"`,
    '',
    `# Wait up to ${timeoutSecs}s for completion, then kill`,
    `for i in $(seq 1 ${intervals}); do`,
    '  sleep 10',
    `  if ! flt list 2>/dev/null | grep -q "${name}"; then`,
    `    echo "$(date -u +%Y-%m-%dT%H:%M:%SZ) ${name} already exited"`,
    '    exit 0',
    '  fi',
    'done',
    '',
    `echo "$(date -u +%Y-%m-%dT%H:%M:%SZ) ${name} timed out after ${timeoutSecs}s, killing"`,
    `flt kill ${name} 2>/dev/null`,
    '',
  ].join('\n')
}

// ── Crontab I/O ──────────────────────────────────────────────────────────────

function readCrontab(): string {
  try {
    return execSync('crontab -l 2>/dev/null', { encoding: 'utf-8' })
  } catch {
    return ''
  }
}

function writeCrontab(content: string): void {
  const tmp = join(tmpdir(), `flt-crontab-${process.pid}.txt`)
  try {
    writeFileSync(tmp, content)
    execSync(`crontab ${tmp}`)
  } finally {
    try { unlinkSync(tmp) } catch {}
  }
}

// ── Crontab line parsing ─────────────────────────────────────────────────────

export interface CronEntry {
  schedule: string
  scriptPath: string
  name: string
  logPath: string
}

export function parseCrontabLines(content: string): CronEntry[] {
  const entries: CronEntry[] = []
  for (const line of content.split('\n')) {
    const trimmed = line.trim()
    if (!trimmed || trimmed.startsWith('#')) continue
    if (!trimmed.includes('flt')) continue

    // cron line: 5-field schedule + rest
    const parts = trimmed.split(/\s+/)
    if (parts.length < 6) continue
    const schedule = parts.slice(0, 5).join(' ')
    const rest = parts.slice(5).join(' ')

    // Script is the first token (before >> redirect)
    const scriptPath = rest.split(/\s+/)[0]
    const nameMatch = scriptPath.match(/cron-([^/\s]+)$/)
    if (!nameMatch) continue
    const name = nameMatch[1]

    const logMatch = rest.match(/>> ([^\s]+)/)
    const logPath = logMatch ? logMatch[1] : ''

    entries.push({ schedule, scriptPath, name, logPath })
  }
  return entries
}

// ── Command implementations ──────────────────────────────────────────────────

function fltBin(): string {
  return join(process.env.HOME!, '.flt', 'bin')
}

function fltLogs(): string {
  return join(process.env.HOME!, '.flt', 'logs')
}

function padRight(s: string, n: number): string {
  const visible = s.replace(/\x1b\[[0-9;]*m/g, '')
  return s + ' '.repeat(Math.max(0, n - visible.length))
}

function formatAge(ms: number): string {
  const secs = Math.floor(ms / 1000)
  if (secs < 60) return `${secs}s`
  const mins = Math.floor(secs / 60)
  if (mins < 60) return `${mins}m`
  const hours = Math.floor(mins / 60)
  if (hours < 24) return `${hours}h`
  return `${Math.floor(hours / 24)}d`
}

export function cronList(): void {
  const entries = parseCrontabLines(readCrontab())
  if (entries.length === 0) {
    console.log('No flt cron entries found. Use "flt cron add <name>" to create one.')
    return
  }

  const state = loadState()

  for (const entry of entries) {
    const human = cronToHuman(entry.schedule)

    const agent = state.agents[entry.name]
    let aliveStr: string
    if (agent && tmux.hasSession(agent.tmuxSession)) {
      const status = agent.status ?? 'unknown'
      aliveStr = `\x1b[32malive\x1b[0m (${status})`
    } else {
      aliveStr = '\x1b[90mdead\x1b[0m'
    }

    let lastRunStr = 'never'
    if (entry.logPath && existsSync(entry.logPath)) {
      lastRunStr = `${formatAge(Date.now() - statSync(entry.logPath).mtimeMs)} ago`
    }

    console.log(
      `${padRight(human, 14)}  ${padRight(entry.name, 20)}  ${padRight(aliveStr, 20)}  (last run: ${lastRunStr})`
    )
  }
}

export interface CronAddOpts {
  every: string
  send?: string
  spawn?: boolean
  preset?: string
  dir?: string
  timeout?: string
  parent?: string
  bootstrap?: string
}

export function cronAdd(name: string, opts: CronAddOpts): void {
  if (!opts.every) throw new Error('--every is required')
  if (!opts.send && !opts.spawn) throw new Error('Either --send or --spawn is required')
  if (opts.send && opts.spawn) throw new Error('Cannot use both --send and --spawn')
  if (opts.spawn && !opts.preset) throw new Error('--preset is required with --spawn')
  if (!/^[a-zA-Z0-9_-]+$/.test(name)) throw new Error('Name must be alphanumeric with dashes/underscores only')

  const cronExpr = intervalToCron(opts.every)
  const binDir = fltBin()
  const logsDir = fltLogs()
  const scriptPath = join(binDir, `cron-${name}`)
  const logPath = join(logsDir, `cron-${name}.log`)

  const current = readCrontab()
  if (current.includes(scriptPath)) {
    throw new Error(`Crontab entry for "${name}" already exists. Use "flt cron remove ${name}" first.`)
  }

  mkdirSync(binDir, { recursive: true })
  mkdirSync(logsDir, { recursive: true })

  const timeoutSecs = parseTimeout(opts.timeout ?? '5m')
  const script = generateScript(name, {
    send: opts.send,
    spawn: opts.spawn,
    preset: opts.preset,
    dir: opts.dir,
    timeoutSecs,
    parent: opts.parent,
    bootstrap: opts.bootstrap,
    binPath: process.env.PATH,
  })

  writeFileSync(scriptPath, script, { mode: 0o755 })

  const entry = `${cronExpr} ${scriptPath} >> ${logPath} 2>&1`
  const newCrontab = (current.trimEnd() ? current.trimEnd() + '\n' : '') + entry + '\n'
  writeCrontab(newCrontab)

  console.log(`Added cron-${name}: ${cronToHuman(cronExpr)} → ${scriptPath}`)
}

export function cronRemove(name: string): void {
  const scriptPath = join(fltBin(), `cron-${name}`)

  const current = readCrontab()
  if (!current.includes(`cron-${name}`)) {
    throw new Error(`No crontab entry found for "${name}".`)
  }

  const newCrontab = current
    .split('\n')
    .filter(line => !line.includes(`cron-${name}`))
    .join('\n')
    .trimEnd()

  writeCrontab(newCrontab ? newCrontab + '\n' : newCrontab)

  if (existsSync(scriptPath)) {
    unlinkSync(scriptPath)
    console.log(`Removed cron-${name}: crontab entry and script deleted.`)
  } else {
    console.log(`Removed cron-${name}: crontab entry deleted (script not found at ${scriptPath}).`)
  }
}
